-- Hand-written (not autogenerated): renames/removes LoanStatus enum values with live data
-- present, which `prisma migrate dev` cannot express as a plain ALTER TYPE. Uses the
-- standard Postgres "new enum + backfill + swap" pattern so every existing row maps to a
-- semantically equivalent new status instead of failing or losing data.

-- ============ LoanStatus ============

CREATE TYPE "LoanStatus_new" AS ENUM (
  'DRAFT',
  'SUBMITTED',
  'WAITING_LABORAN_APPROVAL',
  'LABORAN_APPROVED',
  'LABORAN_REJECTED',
  'WAITING_HEAD_APPROVAL',
  'HEAD_APPROVED',
  'HEAD_REJECTED',
  'READY_FOR_PICKUP',
  'BORROWED',
  'OVERDUE',
  'RETURN_PENDING_INSPECTION',
  'RETURNED',
  'RETURNED_DAMAGED',
  'RETURNED_LOST',
  'COMPLETED',
  'CANCELLED'
);

ALTER TABLE "loans" ADD COLUMN "status_new" "LoanStatus_new";

-- DIKEMBALIKAN loans map to RETURNED vs RETURNED_DAMAGED based on their own return record's
-- recorded condition, not a blind rename, so Loan.status stays consistent with ReturnRecord.
UPDATE "loans" l SET "status_new" = (
  CASE l."status"::text
    WHEN 'MENUNGGU_DOSEN' THEN 'WAITING_LABORAN_APPROVAL'
    WHEN 'MENUNGGU_LABORAN' THEN 'WAITING_LABORAN_APPROVAL'
    WHEN 'MENUNGGU_KEPALA_LAB' THEN 'WAITING_HEAD_APPROVAL'
    WHEN 'DISETUJUI' THEN 'READY_FOR_PICKUP'
    WHEN 'DITOLAK' THEN 'LABORAN_REJECTED'
    WHEN 'DIAMBIL' THEN 'BORROWED'
    WHEN 'TERLAMBAT' THEN 'OVERDUE'
    WHEN 'DIKEMBALIKAN' THEN (
      CASE COALESCE(
        (SELECT r."kondisiCheck" FROM "return_records" r WHERE r."loanId" = l."id" ORDER BY r."tanggal" DESC LIMIT 1),
        'BAIK'
      )
      WHEN 'BAIK' THEN 'RETURNED'
      ELSE 'RETURNED_DAMAGED'
    END)
    ELSE 'WAITING_LABORAN_APPROVAL'
  END
)::"LoanStatus_new";

ALTER TABLE "loans" ALTER COLUMN "status_new" SET NOT NULL;
ALTER TABLE "loans" DROP COLUMN "status";
ALTER TABLE "loans" RENAME COLUMN "status_new" TO "status";
ALTER TABLE "loans" ALTER COLUMN "status" SET DEFAULT 'WAITING_LABORAN_APPROVAL';

DROP TYPE "LoanStatus";
ALTER TYPE "LoanStatus_new" RENAME TO "LoanStatus";

CREATE INDEX "loans_status_idx" ON "loans"("status");

-- ============ ReturnRecord.kondisiCheck -> kondisi (enum) ============

CREATE TYPE "KondisiPengembalian" AS ENUM (
  'SANGAT_BAIK',
  'BAIK',
  'KURANG_BAIK',
  'RUSAK_RINGAN',
  'RUSAK_BERAT',
  'HILANG'
);

ALTER TABLE "return_records" ADD COLUMN "kondisi" "KondisiPengembalian";

-- Legacy binary values map to the closest new granular value; "RUSAK" defaults to the
-- lighter-severity option since the original form never captured severity.
UPDATE "return_records" SET "kondisi" = (
  CASE "kondisiCheck"
    WHEN 'BAIK' THEN 'BAIK'
    WHEN 'RUSAK' THEN 'RUSAK_RINGAN'
    ELSE 'BAIK'
  END
)::"KondisiPengembalian";

ALTER TABLE "return_records" ALTER COLUMN "kondisi" SET NOT NULL;
ALTER TABLE "return_records" DROP COLUMN "kondisiCheck";

-- ============ Approval: one decision per level per loan ============

ALTER TABLE "approvals" ADD CONSTRAINT "approvals_loanId_level_key" UNIQUE ("loanId", "level");
