import type { CategoryName } from "./kategori";
import type { LocationName } from "./lokasi";

export interface SeedInventoryItem {
  nama: string;
  kategori: CategoryName;
  merk?: string;
  jumlah: number;
  tahun?: number;
  lokasi: LocationName;
  dana?: string;
  deskripsi?: string;
  /** Demo-only override for dashboard/kondisi-chart variety — NOT from the source PDF
   *  (the source lab records mark essentially everything "Berfungsi" as of Jan 2026). */
  kondisi?: "BERFUNGSI" | "PERLU_VERIFIKASI" | "MAINTENANCE" | "RUSAK" | "HILANG";
}

// Transcribed from:
// - "DAFTAR INVENTARIS ALAT LABORATORIUM GEOGRAFI UPI TS.pdf" (items 1-31, 2024/2025 revitalisasi batch)
// - "DAFTAR INVENTARIS ALAT LABORATORIUM GEOGRAFI UPI TS4.pdf" (items 32-159, 2008-2023 RKAT/AQAS/PKKM batch)
export const INVENTARIS: SeedInventoryItem[] = [
  // --- PDF "TS" — Revitalisasi 2024/2025 ---
  { nama: "Komputer All In One Veriton Z4", kategori: "Komputer & Elektronik", merk: "Acer", jumlah: 17, tahun: 2024, lokasi: "Lab PJ SIG Lt.4", dana: "REVITALISASI", deskripsi: "Pengolahan data spasial, citra, dan analisis GIS." },
  { nama: "Komputer Zoan", kategori: "Komputer & Elektronik", merk: "Zoan", jumlah: 2, tahun: 2024, lokasi: "Lab PJ SIG Lt.4", dana: "REVITALISASI", deskripsi: "Pengolahan data survei, pemetaan, dan komputasi pendukung praktikum." },
  { nama: "Smart Board Interactive", kategori: "Komputer & Elektronik", merk: "Hde", jumlah: 1, tahun: 2024, lokasi: "Lab Multimedia/Geo Fisik Lt.4", dana: "REVITALISASI", deskripsi: "Media pembelajaran interaktif untuk presentasi dan praktikum." },
  { nama: "UAV VTOL Trinity Pro", kategori: "UAV & Drone", merk: "Trinity", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Pemetaan wilayah skala luas dengan UAV tipe fixed-wing VTOL." },
  { nama: "Drone DJI Metrice 350 RTK", kategori: "UAV & Drone", merk: "DJI", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Platform UAV untuk pemetaan presisi tinggi dan survei fotogrametri." },
  { nama: "Drone DJI Mavic 3 Multispectral", kategori: "UAV & Drone", merk: "DJI", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Akuisisi data multispektral untuk analisis vegetasi dan lingkungan." },
  { nama: "Drone Mavic 3 Enterprise", kategori: "UAV & Drone", merk: "DJI", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Pemetaan detail, inspeksi objek, dan dokumentasi lapangan." },
  { nama: "Drone EVO II Pro V3", kategori: "UAV & Drone", merk: "Autel", jumlah: 5, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Akuisisi foto udara resolusi tinggi untuk pemetaan detail." },
  { nama: "Total Station", kategori: "Alat Survei & Geodesi", merk: "Sokkia", jumlah: 5, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Pengukuran sudut dan jarak untuk survei terestris dan pemetaan topografi." },
  { nama: "Sensor Lidar Zenmuse L2", kategori: "UAV & Drone", merk: "DJI", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Akuisisi data point cloud untuk pemodelan 3D dan topografi detail." },
  { nama: "GNSS D RTK-2", kategori: "Alat Survei & Geodesi", merk: "DJI", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Stasiun referensi GNSS untuk koreksi RTK UAV dan survei presisi tinggi." },
  { nama: "GNSS E-SURVEY E300 Pro", kategori: "Alat Survei & Geodesi", merk: "E-Survey", jumlah: 6, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Penentuan posisi presisi tinggi untuk survei dan pemetaan." },
  { nama: "GNSS Trimble R4S", kategori: "Alat Survei & Geodesi", merk: "Trimble", jumlah: 2, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Penentuan koordinat presisi tinggi untuk pengukuran geodetik." },
  { nama: "3D Printer", kategori: "Komputer & Elektronik", merk: "Flashforge", jumlah: 2, tahun: 2024, lokasi: "Lab Multimedia/Geo Fisik Lt.4", dana: "REVITALISASI", deskripsi: "Pembuatan model fisik hasil pemodelan 3D dan visualisasi data spasial." },
  { nama: "Printer / Plotter A0", kategori: "Komputer & Elektronik", merk: "Epson SC-T5430M", jumlah: 1, tahun: 2024, lokasi: "Lab PJ SIG Lt.4", dana: "REVITALISASI", deskripsi: "Pencetakan peta dan layout ukuran besar." },
  { nama: "Oven Tanah (Dry Oven) Bio-140L", kategori: "Uji Tanah & Air", merk: "BIOLABTEK", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "REVITALISASI", deskripsi: "Pengeringan sampel tanah untuk analisis kadar air." },
  { nama: "Weather Station Digital TNHY-13", kategori: "Klimatologi & Cuaca", merk: "BIOLABTEK", jumlah: 1, tahun: 2024, lokasi: "Lab Geografi Teknik Lt.3", dana: "UPI", deskripsi: "Pengukuran parameter cuaca (suhu, kelembapan, curah hujan, dll)." },
  { nama: "Drone DJI Air 3", kategori: "UAV & Drone", merk: "DJI", jumlah: 2, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Akuisisi foto/video udara untuk dokumentasi dan pemetaan skala kecil." },
  { nama: "Weather Station AWS/Wireless Davis Vantage Pro 2 Plus 6163", kategori: "Klimatologi & Cuaca", merk: "Davis", jumlah: 1, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Pemantauan kondisi cuaca sebagai data pendukung survei lapangan." },
  { nama: "GPS Handheld Garmin Montana 750i", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 3, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Navigasi lapangan dan pencatatan koordinat lokasi." },
  { nama: "Water Quality Kit Test Hanna Hi 3817", kategori: "Uji Tanah & Air", merk: "Hanna", jumlah: 2, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Pengukuran parameter kualitas air secara in-situ." },
  { nama: "Soil Tester Takemura DM-5", kategori: "Uji Tanah & Air", merk: "Takemura", jumlah: 4, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Pengukuran parameter tanah (pH, kelembapan, dll) di lapangan." },
  { nama: "Termometer Infrared Microlife FR1DL1", kategori: "Klimatologi & Cuaca", merk: "Microlife", jumlah: 2, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Pengukuran suhu permukaan tanpa kontak." },
  { nama: "Meteran Roll Tembaga 50m", kategori: "Alat Survei & Geodesi", merk: "Yamayo Pro Silver Seven", jumlah: 4, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Pengukuran jarak lapangan untuk kegiatan survei." },
  { nama: "Soil Color Charts", kategori: "Geologi", merk: "Munsell Soil Color by X-Rite", jumlah: 2, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Identifikasi warna tanah untuk klasifikasi dan deskripsi tanah." },
  { nama: "Printer Sure Color", kategori: "Komputer & Elektronik", merk: "Epson SC-T 3130N", jumlah: 1, tahun: 2024, lokasi: "Lab Integrasi GIS", dana: "UPI", deskripsi: "Pencetakan peta tematik dan hasil visualisasi data." },
  { nama: "Digital Microscope", kategori: "Geologi", merk: "Dino-Lite Edge 3.0 AM73915 Series", jumlah: 1, tahun: 2025, lokasi: "Lab Survei Pemetaan Geosfer", dana: "UPI", deskripsi: "Observasi detail sampel tanah/mineral skala mikro." },
  { nama: "Geolistrik Multichannel", kategori: "Uji Tanah & Air", merk: "ADMT-400SX-32D", jumlah: 2, tahun: 2025, lokasi: "Lab Survei Pemetaan Geosfer", dana: "REVITALISASI", deskripsi: "Pengukuran resistivitas bawah permukaan untuk investigasi geologi/air tanah." },
  { nama: "Meteran Roll Fiber 50m", kategori: "Alat Survei & Geodesi", merk: "Deli", jumlah: 10, tahun: 2025, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran jarak lapangan sebagai alat bantu survei." },
  { nama: "Rambu Ukur 3 Meter", kategori: "Alat Survei & Geodesi", merk: "LOC", jumlah: 10, tahun: 2025, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Alat baca ukur elevasi pada pengukuran waterpass/leveling." },
  { nama: "Nivo Pole", kategori: "Alat Survei & Geodesi", merk: "Air Pass", jumlah: 10, tahun: 2025, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Untuk leveling tongkat ukur reflektor, GNSS/Total Station untuk penentuan posisi titik." },

  // --- PDF "TS4" — RKAT/AQAS/PKKM 2008-2023 ---
  { nama: "Lup", kategori: "Optik & Observasi", jumlah: 4, tahun: 2008, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Membantu pengamatan objek kecil di lapangan/lab.", kondisi: "PERLU_VERIFIKASI" },
  { nama: "Psikometer Asman", kategori: "Klimatologi & Cuaca", jumlah: 1, tahun: 2008, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur kelembapan udara dan suhu basah-kering.", kondisi: "PERLU_VERIFIKASI" },
  { nama: "Digital Theodolite", kategori: "Alat Survei & Geodesi", jumlah: 1, tahun: 2009, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur sudut horizontal dan vertikal pada survei terestris.", kondisi: "PERLU_VERIFIKASI" },
  { nama: "Kompas Suunto Clinometer PM-5", kategori: "Alat Survei & Geodesi", merk: "Suunto", jumlah: 1, tahun: 2014, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Menentukan arah dan orientasi lapangan." },
  { nama: "GPS Garmin eTrex 30", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Menentukan posisi koordinat lokasi di lapangan." },
  { nama: "GPS Garmin GPSmap Oregon 650", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Menentukan posisi koordinat lokasi di lapangan." },
  { nama: "Palu Geologi", kategori: "Geologi", merk: "Estwint", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengambil dan memecah sampel batuan." },
  { nama: "Kompas Geologi DQL-8", kategori: "Geologi", merk: "DQL-8", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur jurus dan kemiringan lapisan batuan." },
  { nama: "Anemometer Lutron ABH 4224", kategori: "Klimatologi & Cuaca", merk: "Lutron", jumlah: 2, tahun: 2015, lokasi: "Lab Prodi Pendidikan Geografi", dana: "RKAT", deskripsi: "Mengukur kecepatan angin." },
  { nama: "GPS Garmin 60 Csx", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 3, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Navigasi lapangan dan pencatatan koordinat." },
  { nama: "Theodolite", kategori: "Alat Survei & Geodesi", jumlah: 8, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur sudut untuk survei dan pemetaan." },
  { nama: "Waterpas", kategori: "Alat Survei & Geodesi", jumlah: 3, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran beda tinggi (levelling)." },
  { nama: "Rambu Ukur", kategori: "Alat Survei & Geodesi", jumlah: 14, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Alat baca ukur tinggi pada pengukuran waterpass." },
  { nama: "Statif Tripod", kategori: "Alat Survei & Geodesi", merk: "Topcon, Mysurv, Sokia", jumlah: 9, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Penyangga alat ukur survei." },
  { nama: "Total Station Topcon GTS 235N", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 2, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran sudut dan jarak untuk pemetaan topografi." },
  { nama: "Meteran", kategori: "Alat Survei & Geodesi", merk: "ATS", jumlah: 5, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran jarak manual di lapangan." },
  { nama: "Prisma Box", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 4, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor untuk pengukuran jarak Total Station." },
  { nama: "GPS", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 2, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Menentukan koordinat lokasi." },
  { nama: "Rambu Ukur", kategori: "Alat Survei & Geodesi", jumlah: 2, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pembacaan tinggi pada pengukuran leveling." },
  { nama: "Handy Talky", kategori: "Alat Bantu Lapangan", jumlah: 2, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Komunikasi tim survei di lapangan." },
  { nama: "Steoroskop", kategori: "Optik & Observasi", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengamati foto udara secara 3D." },
  { nama: "Prisma ADS", kategori: "Alat Survei & Geodesi", merk: "ADS", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor untuk pengukuran Total Station." },
  { nama: "Rambu Ukur", kategori: "Alat Survei & Geodesi", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pembacaan tinggi elevasi." },
  { nama: "Handy Talky", kategori: "Alat Bantu Lapangan", merk: "Firstcom", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Komunikasi lapangan." },
  { nama: "Rambu Ukur", kategori: "Alat Survei & Geodesi", jumlah: 1, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Alat bantu pengukuran elevasi." },
  { nama: "Teropong Bushnell", kategori: "Optik & Observasi", jumlah: 2, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Observasi objek jarak jauh di lapangan." },
  { nama: "Theodolite To", kategori: "Alat Survei & Geodesi", jumlah: 2, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran sudut survei terestris." },
  { nama: "Waterpass", kategori: "Alat Survei & Geodesi", jumlah: 2, tahun: 2015, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran beda tinggi." },
  { nama: "Barometer Aneroid", kategori: "Klimatologi & Cuaca", merk: "Daiko DB-150", jumlah: 2, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur tekanan udara." },
  { nama: "Hygrometer Analog", kategori: "Klimatologi & Cuaca", merk: "Gemlead", jumlah: 4, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur kelembapan udara." },
  { nama: "Ph Meter", kategori: "Uji Tanah & Air", merk: "Extech PH-100", jumlah: 2, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur tingkat keasaman air/tanah." },
  { nama: "GPS Garmin Etrex 10", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 2, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Menentukan koordinat posisi." },
  { nama: "Altimeter", kategori: "Alat Survei & Geodesi", merk: "Bruton G3 Pro", jumlah: 1, tahun: 2016, lokasi: "Lab Prodi Pendidikan Geografi", dana: "RKAT", deskripsi: "Mengukur ketinggian tempat." },
  { nama: "Echosounder", kategori: "Uji Tanah & Air", jumlah: 1, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur kedalaman perairan." },
  { nama: "Waterpass", kategori: "Alat Survei & Geodesi", jumlah: 1, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran elevasi." },
  { nama: "GPS Garmin 78s", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 1, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Navigasi dan posisi lapangan." },
  { nama: "Handy Talky", kategori: "Alat Bantu Lapangan", jumlah: 4, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Komunikasi lapangan." },
  { nama: "Theodolite Digital", kategori: "Alat Survei & Geodesi", merk: "Nikon NE101", jumlah: 1, tahun: 2016, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran sudut terestris digital." },
  { nama: "Thermometer Hygrometer", kategori: "Klimatologi & Cuaca", merk: "THIOIE", jumlah: 20, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur suhu dan kelembapan udara." },
  { nama: "Barometer Analog", kategori: "Klimatologi & Cuaca", jumlah: 18, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur tekanan udara.", kondisi: "MAINTENANCE" },
  { nama: "Anemometer", kategori: "Klimatologi & Cuaca", merk: "HT-81", jumlah: 4, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur kecepatan angin." },
  { nama: "Bor Biopori Spiral", kategori: "Alat Bantu Lapangan", jumlah: 3, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pembuatan lubang biopori dan sampling tanah." },
  { nama: "Ph Meter", kategori: "Uji Tanah & Air", merk: "Lutron YK 2001 PHA PH", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur pH air/tanah." },
  { nama: "Double Ring Infiltration", kategori: "Uji Tanah & Air", jumlah: 3, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur laju infiltrasi air ke tanah." },
  { nama: "Palu Geologi Pipih", kategori: "Geologi", merk: "Estwing (batuan sedimen)", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengambilan sampel batuan." },
  { nama: "Timbangan Digital", kategori: "Alat Bantu Lapangan", merk: "Notebook series", jumlah: 1, tahun: 2017, lokasi: "Lab Prodi Pendidikan Geografi", dana: "RKAT", deskripsi: "Menimbang berat sampel." },
  { nama: "Drone DJI Phantom 4 Pro", kategori: "UAV & Drone", merk: "DJI", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Akuisisi data foto/video udara." },
  { nama: "Automatic Level", kategori: "Alat Survei & Geodesi", merk: "Topcon AT-B4A", jumlah: 2, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran beda tinggi presisi." },
  { nama: "Rambu Ukur Pole Stick", kategori: "Alat Survei & Geodesi", jumlah: 6, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Alat baca leveling." },
  { nama: "GPS Garmin Etrex 30", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Penentuan koordinat." },
  { nama: "Total Station Topcon GTSES65", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pemetaan dan pengukuran detail." },
  { nama: "Prisma Single", kategori: "Alat Survei & Geodesi", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor tunggal untuk Total Station." },
  { nama: "Rambu Ukur Pole Stik Jalon 2,5 Meter", kategori: "Alat Survei & Geodesi", jumlah: 7, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pembacaan elevasi." },
  { nama: "Prisma Tribrach Polygon", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 2, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor Total Station." },
  { nama: "GPS Maps Garmin 64 S", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Navigasi lapangan berbasis peta." },
  { nama: "Automatic Level 2LS Orion", kategori: "Alat Survei & Geodesi", merk: "Sokia", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran leveling presisi." },
  { nama: "Abney Hand Level", kategori: "Alat Survei & Geodesi", merk: "Seco", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran kemiringan lereng." },
  { nama: "GPS Garmin 30 e trex", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 2, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Penentuan posisi." },
  { nama: "Rambu Ukur", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 1, tahun: 2017, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Alat bantu leveling." },
  { nama: "Double Ring Infiltration", kategori: "Uji Tanah & Air", jumlah: 2, tahun: 2018, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Uji laju infiltrasi tanah." },
  { nama: "Total Station Sokkia Set 60 Type Set 65 KD1340", kategori: "Alat Survei & Geodesi", merk: "Sokkia", jumlah: 2, tahun: 2018, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran jarak dan sudut." },
  { nama: "Prisma Set HD 19", kategori: "Alat Survei & Geodesi", jumlah: 5, tahun: 2018, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor Total Station." },
  { nama: "Pocket Stereoskop 4X", kategori: "Optik & Observasi", jumlah: 2, tahun: 2018, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Observasi foto udara 3D skala kecil." },
  { nama: "Optical Square Penta Prisma", kategori: "Alat Survei & Geodesi", jumlah: 6, tahun: 2018, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Penentuan sudut siku di lapangan." },
  { nama: "Keyboard + Mouse", kategori: "Komputer & Elektronik", merk: "Logitech MK545 Wireless", jumlah: 1, tahun: 2018, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Perangkat input komputer." },
  { nama: "CPU / PC Workstation", kategori: "Komputer & Elektronik", merk: "HP PC Omen 880-015D", jumlah: 1, tahun: 2018, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengolahan data survei dan GIS." },
  { nama: "Kompas Compass Tandem & Clinometer", kategori: "Alat Survei & Geodesi", merk: "Suunto", jumlah: 3, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Penentuan arah lapangan." },
  { nama: "Geosystem", kategori: "Alat Survei & Geodesi", merk: "Leica Geosystem Disto D2", jumlah: 3, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Perangkat pengukuran geospasial." },
  { nama: "Termometer Batang -5° - 110°C", kategori: "Klimatologi & Cuaca", jumlah: 35, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Mengukur suhu." },
  { nama: "Total Station Minds MTS 02", kategori: "Alat Survei & Geodesi", merk: "Minds", jumlah: 1, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Pengukuran detail topografi." },
  { nama: "Tripod", kategori: "Alat Survei & Geodesi", merk: "Minds", jumlah: 2, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Penyangga alat survei." },
  { nama: "Prisma", kategori: "Alat Survei & Geodesi", merk: "Minds", jumlah: 1, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor pengukuran jarak." },
  { nama: "Single Prisma", kategori: "Alat Survei & Geodesi", merk: "Minds", jumlah: 1, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor tunggal Total Station." },
  { nama: "Prisma", kategori: "Alat Survei & Geodesi", merk: "Nikon", jumlah: 1, tahun: 2019, lokasi: "Lab Survei Pemetaan Geosfer", dana: "RKAT", deskripsi: "Reflektor Total Station.", kondisi: "HILANG" },
  { nama: "Ring Sample Tanah", kategori: "Uji Tanah & Air", jumlah: 48, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengambil sampel tanah utuh." },
  { nama: "Flowmeter", kategori: "Uji Tanah & Air", merk: "Flowatch FL-03", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur debit aliran air." },
  { nama: "Alat Uji Kualitas Air", kategori: "Uji Tanah & Air", merk: "7 in 1 Multiparameter PC 900 Water Test Kit", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur parameter kualitas air." },
  { nama: "Weather Station", kategori: "Klimatologi & Cuaca", merk: "Davis 6152 Vantage Pro2 Wireless", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pemantauan parameter cuaca." },
  { nama: "Palu Geologi Runcing", kategori: "Geologi", merk: "Estwing E3-22P (batuan beku)", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pengambilan sampel batuan." },
  { nama: "Palu Geologi Pipih", kategori: "Geologi", merk: "Estwing E3-20BLC (batuan sedimen)", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pengambilan sampel batuan." },
  { nama: "Timbangan Digital", kategori: "Alat Bantu Lapangan", merk: "Akurasi 0.01g, Max 500g", jumlah: 7, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Menimbang sampel." },
  { nama: "GPS", kategori: "Alat Survei & Geodesi", merk: "Garmin GPS Map 64s", jumlah: 4, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Penentuan posisi." },
  { nama: "Water Current Meter Stick", kategori: "Uji Tanah & Air", merk: "FP-111", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur kecepatan arus air." },
  { nama: "Infiltrometer Digital", kategori: "Uji Tanah & Air", merk: "Turc Tec", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur laju infiltrasi tanah." },
  { nama: "Infiltrometer Manual", kategori: "Uji Tanah & Air", merk: "Ring 15cm/30cm", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur laju infiltrasi tanah secara manual." },
  { nama: "Ph Meter", kategori: "Uji Tanah & Air", merk: "EZ-9909 5 in 1 Salinity TDS EC", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur pH." },
  { nama: "Barometer Mini 8 in 1", kategori: "Klimatologi & Cuaca", merk: "LCD Digital Altimeter Barometer Thermo Compass", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur tekanan udara." },
  { nama: "Higrometer Digital Mini 3 in 1", kategori: "Klimatologi & Cuaca", merk: "TL300", jumlah: 7, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur kelembapan udara." },
  { nama: "Termometer Max-Min", kategori: "Klimatologi & Cuaca", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur suhu." },
  { nama: "Total Station Topcon GM 55", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 3, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pemetaan terestris." },
  { nama: "Waterpass Topcon AT-B4", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 3, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pengukuran beda tinggi." },
  { nama: "Prisma Backsight", kategori: "Alat Survei & Geodesi", merk: "Polygon Topcon", jumlah: 3, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Titik referensi arah pengukuran Total Station." },
  { nama: "Meteran Roll", kategori: "Alat Survei & Geodesi", merk: "Yamayo Silver Seven 50 Meter", jumlah: 8, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pengukuran jarak manual." },
  { nama: "Helm Teknik", kategori: "Alat Bantu Lapangan", merk: "Safety Strap MSA Lokal SNI", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Alat keselamatan kerja lapangan." },
  { nama: "Handy Talky", kategori: "Alat Bantu Lapangan", merk: "JC-369 VHF", jumlah: 7, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Komunikasi lapangan.", kondisi: "MAINTENANCE" },
  { nama: "Rambu Ukur 5 Meter", kategori: "Alat Survei & Geodesi", merk: "Leveling Staff", jumlah: 6, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Alat baca leveling." },
  { nama: "GPS Garmin 64S", kategori: "Alat Survei & Geodesi", merk: "Garmin", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Penentuan koordinat." },
  { nama: "Psychrometer", kategori: "Klimatologi & Cuaca", merk: "Elcometer 116 Whirling & Sling Hygrometers G116A", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur suhu basah-kering dan kelembapan." },
  { nama: "Geolistrik", kategori: "Uji Tanah & Air", merk: "New Neoresist Meter", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Survei resistivitas bawah permukaan." },
  { nama: "Navigasi Satelit GNSS", kategori: "Alat Survei & Geodesi", merk: "Sokkia GRX3", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Penentuan posisi berbasis satelit." },
  { nama: "Tabung Reaksi 16 Ml", kategori: "Alat Bantu Lapangan", jumlah: 24, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Wadah reaksi kimia skala kecil." },
  { nama: "Pipet", kategori: "Alat Bantu Lapangan", jumlah: 10, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Memindahkan cairan volume kecil." },
  { nama: "Gelas Ukur", kategori: "Alat Bantu Lapangan", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur volume cairan." },
  { nama: "Tabung Reaksi", kategori: "Alat Bantu Lapangan", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Wadah reaksi kimia." },
  { nama: "Tabung Reaksi", kategori: "Alat Bantu Lapangan", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Wadah reaksi kimia." },
  { nama: "Tabung Reaksi", kategori: "Alat Bantu Lapangan", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Wadah reaksi kimia.", kondisi: "RUSAK" },
  { nama: "Globe/Bola Dunia", kategori: "Alat Bantu Lapangan", merk: "D=42.5cm", jumlah: 5, tahun: 2020, lokasi: "Lab Prodi Pendidikan Geografi", dana: "AQAS", deskripsi: "Media pembelajaran geografi global." },
  { nama: "Total Station Topcon GM-55", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pemetaan detail topografi." },
  { nama: "Waterpass Topcon AT-B4", kategori: "Alat Survei & Geodesi", merk: "Topcon", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pengukuran beda tinggi." },
  { nama: "Meteran Roll", kategori: "Alat Survei & Geodesi", merk: "Yamayo VR 50 Meter", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Pengukuran jarak." },
  { nama: "Handy Talky", kategori: "Alat Bantu Lapangan", merk: "Jacom JC-369", jumlah: 5, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Komunikasi tim lapangan." },
  { nama: "Globe/Bola Dunia", kategori: "Alat Bantu Lapangan", merk: "D=42.5cm", jumlah: 2, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Media pembelajaran geografi." },
  { nama: "Termometer", kategori: "Uji Tanah & Air", merk: "EZ-9908 PH TDS EC", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Mengukur suhu." },
  { nama: "GNSS", kategori: "Alat Survei & Geodesi", merk: "Hemisphere S321", jumlah: 1, tahun: 2020, lokasi: "Lab Survei Pemetaan Geosfer", dana: "AQAS", deskripsi: "Penentuan posisi presisi tinggi." },
  { nama: "Kompas", kategori: "Alat Survei & Geodesi", merk: "Brunton 5030 Geo Lite Transit", jumlah: 3, tahun: 2021, lokasi: "Lab Survei Pemetaan Geosfer", dana: "PKKM", deskripsi: "Penentuan arah." },
  { nama: "Waterpass", kategori: "Alat Survei & Geodesi", merk: "Topcon ATB-4A", jumlah: 1, tahun: 2021, lokasi: "Lab Survei Pemetaan Geosfer", dana: "PKKM", deskripsi: "Pengukuran leveling." },
  { nama: "Water Meter Temp Tester", kategori: "Uji Tanah & Air", merk: "7 in 1 Salt COM600", jumlah: 3, tahun: 2021, lokasi: "Lab Survei Pemetaan Geosfer", dana: "PKKM", deskripsi: "Mengukur debit/volume air." },
  { nama: "Nas Tower", kategori: "Komputer & Elektronik", merk: "ASUSTOR AS6604T", jumlah: 1, tahun: 2022, lokasi: "Lab Survei Pemetaan Geosfer", dana: "PKKM", deskripsi: "Penyimpanan data terpusat." },
  { nama: "Drone DJI Phantom 4 Pro+ V2.0", kategori: "UAV & Drone", merk: "DJI", jumlah: 2, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Akuisisi data udara." },
  { nama: "Headphone", kategori: "Multimedia & Dokumentasi", merk: "Saramonic BH-600", jumlah: 4, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Monitoring audio dokumentasi." },
  { nama: "Camera Mirrorless", kategori: "Multimedia & Dokumentasi", merk: "Sony a7 IV", jumlah: 1, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Dokumentasi foto lapangan." },
  { nama: "Handycam", kategori: "Multimedia & Dokumentasi", merk: "Sony CX405", jumlah: 1, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Dokumentasi video kegiatan." },
  { nama: "Mixer Audio", kategori: "Multimedia & Dokumentasi", merk: "Behringer X1204 USB", jumlah: 1, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Pengolah input audio." },
  { nama: "Microphone", kategori: "Multimedia & Dokumentasi", merk: "Saramonic SR-MV7000 XLR USB", jumlah: 4, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Perekam suara lapangan/studio." },
  { nama: "Tripod", kategori: "Multimedia & Dokumentasi", merk: "K&F SA254C Ballhead", jumlah: 2, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Penyangga kamera/peralatan." },
  { nama: "CPU / PC Workstation", kategori: "Komputer & Elektronik", merk: "Asus ROG G35CG-9K3123802W", jumlah: 1, tahun: 2022, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Pengolahan data dan multimedia." },
  { nama: "Portable Sound System", kategori: "Multimedia & Dokumentasi", merk: "TOA ZW-G10CB-AS", jumlah: 1, tahun: 2023, lokasi: "Lab Survei Pemetaan Geosfer", dana: "PKKM", deskripsi: "Sistem audio portabel untuk kegiatan lapangan." },
  { nama: "Studio Lighting", kategori: "Multimedia & Dokumentasi", merk: "Takara HELIO 480D", jumlah: 2, tahun: 2023, lokasi: "Lab Prodi Pendidikan Geografi", dana: "PKKM", deskripsi: "Pencahayaan untuk dokumentasi visual." },
];
